BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
EXTRAKEY_ENABLE = yes       # Audio control and System control
COMMAND_ENABLE = yes        # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
BOOTLOADER = atmel-dfu
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
CAPS_WORD_ENABLE = yes
# LTO_ENABLE = yes
